-- Assemble Part IV of kuu.md: every page of the manual, in a deliberate
-- reading order, inlined so an agent can read everything up front.
--
-- The bundle is generated rather than hand-maintained, because forty pages
-- copied by hand drift from their originals and the copy is the one people
-- read.  test/cases/bundle.lua regenerates it and fails when kuu.md is stale.
--
--   kuu tools/bundle_docs.lua            print the bundle
--   kuu tools/bundle_docs.lua --write    rewrite kuu.md's Part IV in place
global none
global <const> require, ipairs, error, os, io, table, tostring, assert

local fs = require "fs"
local rt = require "rt"

-- The marker after which kuu.md is generated.  Everything above it is written
-- by hand; everything from it down is this file's output.
local MARKER = "# Part IV — the complete manual"

-- A deliberate order: the map, the one page to read first, then getting a
-- project going, the palette, the recipes, and finally the record.
local ORDER = {
  "index", "pitfalls",
  "adopting", "task", "check", "cli",
  "proc", "fs", "http", "net", "sched", "json", "csv", "ini",
  "hash", "text", "re", "time", "archive", "log", "err",
  "mem", "sync", "sys", "reg", "env", "svc", "evt", "pty",
  "powershell", "cookbook",
  "inheritance", "roadmap", "shortcomings", "stability", "toolchain",
  "upgrading-0.9", "upgrading-0.8", "upgrading-0.7", "upgrading-0.6",
}

local function root()
  return fs.dirname(fs.dirname(fs.canon(rt.program).path))
end

-- GitHub's anchor for a heading: lower case, dots dropped, spaces to dashes.
local function anchor(name)
  return (name:lower():gsub("%.", ""))
end

-- Demote every heading one level so the pages nest under Part IV, and rewrite
-- cross-page links to anchors inside this document.  Headings inside fenced
-- code blocks are left alone.
local function transform(text)
  local out, fenced = {}, false
  for raw in (text .. "\n"):gmatch("([^\n]*)\n") do
    local line = raw
    if line:match("^```") then fenced = not fenced end
    if not fenced then
      if line:match("^#") then line = "#" .. line end
      line = line:gsub("%]%((%w[%w%-%.]-)%.md#[%w%-]+%)", function(page)
        return "](#" .. anchor(page) .. ")"
      end)
      line = line:gsub("%]%((%w[%w%-%.]-)%.md%)", function(page)
        return "](#" .. anchor(page) .. ")"
      end)
    end
    out[#out + 1] = line
  end
  return table.concat(out, "\n")
end

local function build(docs)
  local parts = {
    MARKER,
    "",
    "Every page of the manual, inlined. This is the same text `kuu docs`",
    "serves from inside the executable, assembled here so that everything kuu",
    "knows about itself can be read in one pass without querying anything.",
    "",
    "It is generated by `tools/bundle_docs.lua` and checked by the suite; edit",
    "the pages under `docs/`, never this part.",
    "",
  }
  for _, name in ipairs(ORDER) do
    do
      local path = docs .. "/" .. name .. ".md"
      local text = fs.read(path)
      if not text then error("no such page: " .. path) end
      parts[#parts + 1] = "---"
      parts[#parts + 1] = ""
      parts[#parts + 1] = transform(text):gsub("%s+$", "")
      parts[#parts + 1] = ""
    end
  end
  return table.concat(parts, "\n")
end

local here = root()
local bundle = build(here .. "/docs")

-- Every page must be in the order, or a new page would silently go missing.
local listed = {}
for _, name in ipairs(ORDER) do listed[name] = true end
local missing = {}
for _, entry in ipairs(fs.list(here .. "/docs").entries) do
  local page = entry.name:match("^(.+)%.md$")
  if page and not listed[page] then missing[#missing + 1] = page end
end
if #missing > 0 then
  io.stderr:write("pages missing from ORDER: ", table.concat(missing, ", "), "\n")
  os.exit(1)
end

if rt.args[1] == "--write" then
  local path = here .. "/kuu.md"
  local current = fs.read(path)
  if not current then error("no kuu.md at " .. path) end
  local head = current:match("^(.-)\n" .. MARKER) or current:gsub("%s+$", "")
  assert(fs.write(path, head:gsub("%s+$", "") .. "\n\n" .. bundle .. "\n"))
  io.write("kuu.md: Part IV regenerated from ", tostring(#ORDER), " pages\n")
else
  io.write(bundle, "\n")
end
