/*
 * embed.c -- a build tool: turn files into a C source with their bytes.
 *
 *   embed OUTPUT.c DIR ...
 *
 * Every regular file under each DIR (one level, sorted by name) becomes an
 * entry in the generated table `ku_payload[]`, named "<dir>/<file>", with its
 * bytes as an unsigned char array.  kuu's `require` and its manual read from
 * that table, so kuu ships its own Lua and documentation inside the executable
 * without kuu having to build kuu: this tool is plain C, compiled by the same
 * gcc as everything else, and run by make.  The output is deterministic.
 */
#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

typedef struct entry {
    char *name;   /* "dir/file" with forward slashes */
    char *path;   /* how to open it */
} entry;

static int compare_entries(const void *a, const void *b)
{
    return strcmp(((const entry *)a)->name, ((const entry *)b)->name);
}

static int collect(const char *dir, entry **entries, size_t *count, size_t *capacity)
{
    char pattern[MAX_PATH];
    snprintf(pattern, sizeof pattern, "%s\\*", dir);
    WIN32_FIND_DATAA data;
    HANDLE find = FindFirstFileA(pattern, &data);
    if (find == INVALID_HANDLE_VALUE) {
        fprintf(stderr, "embed: cannot list %s\n", dir);
        return -1;
    }
    do {
        if (data.dwFileAttributes & FILE_ATTRIBUTE_DIRECTORY) {
            continue;
        }
        if (*count == *capacity) {
            size_t next = *capacity ? *capacity * 2 : 32;
            entry *grown = (entry *)realloc(*entries, next * sizeof *grown);
            if (grown == NULL) {
                FindClose(find);
                return -1;
            }
            *entries = grown;
            *capacity = next;
        }
        size_t dir_length = strlen(dir), name_length = strlen(data.cFileName);
        entry *e = &(*entries)[*count];
        e->name = (char *)malloc(dir_length + 1 + name_length + 1);
        e->path = (char *)malloc(dir_length + 1 + name_length + 1);
        if (e->name == NULL || e->path == NULL) {
            FindClose(find);
            return -1;
        }
        snprintf(e->name, dir_length + 1 + name_length + 1, "%s/%s", dir, data.cFileName);
        snprintf(e->path, dir_length + 1 + name_length + 1, "%s\\%s", dir, data.cFileName);
        for (char *c = e->name; *c; c++) {
            if (*c == '\\') {
                *c = '/';
            }
        }
        (*count)++;
    } while (FindNextFileA(find, &data));
    FindClose(find);
    return 0;
}

int main(int argc, char **argv)
{
    if (argc < 3) {
        fprintf(stderr, "usage: embed OUTPUT.c DIR ...\n");
        return 2;
    }
    entry *entries = NULL;
    size_t count = 0, capacity = 0;
    for (int i = 2; i < argc; i++) {
        if (collect(argv[i], &entries, &count, &capacity) != 0) {
            return 1;
        }
    }
    qsort(entries, count, sizeof *entries, compare_entries);

    FILE *out = fopen(argv[1], "wb");
    if (out == NULL) {
        fprintf(stderr, "embed: cannot write %s\n", argv[1]);
        return 1;
    }
    fprintf(out, "/* generated by tools/embed.c; do not edit */\n#include \"payload.h\"\n\n");
    for (size_t i = 0; i < count; i++) {
        FILE *in = fopen(entries[i].path, "rb");
        if (in == NULL) {
            fprintf(stderr, "embed: cannot read %s\n", entries[i].path);
            fclose(out);
            return 1;
        }
        fprintf(out, "static const unsigned char file_%zu[] = {\n", i);
        unsigned char buffer[4096];
        size_t total = 0, got;
        while ((got = fread(buffer, 1, sizeof buffer, in)) > 0) {
            for (size_t k = 0; k < got; k++) {
                fprintf(out, "%u,%s", buffer[k], ((total + k) % 24 == 23) ? "\n" : "");
            }
            total += got;
        }
        fclose(in);
        fprintf(out, "0};\n"); /* a trailing NUL, so text entries are C strings too */
    }
    fprintf(out, "\nconst ku_payload_entry ku_payload[] = {\n");
    for (size_t i = 0; i < count; i++) {
        fprintf(out, "    {\"%s\", file_%zu, sizeof(file_%zu) - 1},\n", entries[i].name, i, i);
    }
    fprintf(out, "    {NULL, NULL, 0},\n};\nconst size_t ku_payload_count = %zu;\n", count);
    fclose(out);
    return 0;
}
