/*
 * versionrc.c -- a build tool: the version resource, from src/kuu.h.
 *
 *   versionrc OUTPUT.rc
 *
 * Writes the VERSIONINFO resource that makes the file's properties say what
 * `kuu --version` says.  The version is read at compile time from kuu.h, so
 * the two cannot drift; windres compiles the result into the executable.
 * Plain C, compiled by the same gcc as everything else, run by make.
 */
#include "kuu.h"

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char **argv)
{
    if (argc != 2) {
        fprintf(stderr, "usage: versionrc OUTPUT.rc\n");
        return 2;
    }
    unsigned major = 0, minor = 0;
    if (sscanf(KUU_VERSION, "%u.%u", &major, &minor) != 2) {
        fprintf(stderr, "versionrc: KUU_VERSION \"%s\" is not Major.Minor\n", KUU_VERSION);
        return 1;
    }
    FILE *out = fopen(argv[1], "wb");
    if (out == NULL) {
        fprintf(stderr, "versionrc: cannot write %s\n", argv[1]);
        return 1;
    }
    fprintf(out,
            "/* generated by tools/versionrc.c from src/kuu.h; do not edit */\n"
            "1 VERSIONINFO\n"
            "FILEVERSION %u,%u,0,0\n"
            "PRODUCTVERSION %u,%u,0,0\n"
            "FILEFLAGSMASK 0x3fL\n"
            "FILEFLAGS 0x0L\n"
            "FILEOS 0x40004L\n"
            "FILETYPE 0x1L\n"
            "FILESUBTYPE 0x0L\n"
            "BEGIN\n"
            "  BLOCK \"StringFileInfo\"\n"
            "  BEGIN\n"
            "    BLOCK \"040904b0\"\n"
            "    BEGIN\n"
            "      VALUE \"CompanyName\", \"Vincent Vercauteren\"\n"
            "      VALUE \"FileDescription\", \"kuu, a Lua 5.5 runtime for agents on Windows\"\n"
            "      VALUE \"FileVersion\", \"%s\"\n"
            "      VALUE \"InternalName\", \"kuu\"\n"
            "      VALUE \"LegalCopyright\", \"Copyright 2026 Vincent Vercauteren. Apache License 2.0.\"\n"
            "      VALUE \"OriginalFilename\", \"kuu.exe\"\n"
            "      VALUE \"ProductName\", \"kuu\"\n"
            "      VALUE \"ProductVersion\", \"%s\"\n"
            "    END\n"
            "  END\n"
            "  BLOCK \"VarFileInfo\"\n"
            "  BEGIN\n"
            "    VALUE \"Translation\", 0x409, 1200\n"
            "  END\n"
            "END\n",
            major, minor, major, minor, KUU_VERSION, KUU_VERSION);
    fclose(out);
    return 0;
}
